# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/search',
                'doc_host': 'https://LotsOfOrg.github.io',
                'git_url': 'https://github.com/LotsOfOrg/search',
                'lib_path': 'search'},
  'syms': {'search.core': {'search.core.foo': ('core.html#foo', 'search/core.py')}}}
